# This file configures the analyzer, which statically analyzes Dart code to
# check for errors, warnings, and lints.
analyzer:
  errors:
    use_build_context_synchronously: ignore
    deprecated_member_use: ignore

linter:
  rules:
    avoid_print: false
    prefer_single_quotes: true
